---
# tasks


# Bring Services  up
 
  - hosts: webserver
  
    become: true
  
    tasks:
   
      - service: name=apache2 state=started

      
   
- hosts: loadbalancer
  
     become: true
  
     tasks:
   
       - service: name=nginx state=started
#Re-Start My-SQL
     - hosts: database
       become: true
       tasks:
         - name: restart mysql service 
           service: name=mysql state=restarted
         - name: record all logs
           file: path=/etc/ansible/ansible.cfg 
           notify: RSS Feeds
    handler: 
         - name: restart mysql service 
           service: name=mysql state=restarted
